version: "3"

networks:
    LHA:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16
                  gateway: 10.6.0.1

services:
    web:
        image: nginx:latest
        restart: always
        depends_on:
            -   mysql
            -   php-fpm10
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
            - ./docker/data/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/data/nginx/logs/:/var/log/nginx/
        networks:
            LHA:
                ipv4_address: 10.6.0.2
    php-fpm:
        container_name: phpfpm
        build: ./docker/images/php-fpm/
        volumes:
            - .:/var/www/html
            - ./docker/data/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/data/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            - PHP_IDE_CONFIG=serverName=arch
            - XDEBUG_CONFIG=idekey=PHPSTORM
        networks:
            LHA:
                ipv4_address: 10.6.0.4
    mysql:
        container_name: mysql
        image: mysql:8-debian
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "8002:3306"
        networks:
            LHA:
                ipv4_address: 10.6.0.3
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        depends_on:
            -   mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=10.6.0.3
            - PMA_PORT=3306
        ports:
            - "8003:80"
        networks:
            LHA:
                ipv4_address: 10.6.0.5
    mysql-testing:
        container_name: mysql-testing
        image: mysql:8-debian
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "8004:3306"
        networks:
            LHA:
                ipv4_address: 10.6.0.7
    phpmyadmin-testing:
        image: phpmyadmin:latest
        restart: always
        depends_on:
            -   mysql-testing
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=10.6.0.7
            - PMA_PORT=3306
        ports:
            - "8005:80"
        networks:
            LHA:
                ipv4_address: 10.6.0.8
    firefox:
        build: ./docker/images/firefox
        container_name: firefox_lha
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./docker/data/firefox:/home/developer
            - /dev/snd:/dev/snd
        networks:
            LHA:
                ipv4_address: 10.6.0.6
