<?php

declare(strict_types=1);

namespace Src\Domain\User\Properties\UserUpdatedAt\Validators\UserUpdatedAtTimestampPropertyValidator;

use Src\Domain\User\Properties\UserEmailVerifiedAt\Validators\UserVerifiedAtTimestampPropertyValidator\UserVerifiedAtTimestampPropertyWrongRangeException;

class UserUpdatedAtTimestampPropertyWrongRangeException extends UserVerifiedAtTimestampPropertyWrongRangeException
{

}
